In [1]:
import numpy as np

In [179]:
x=np.zeros((7,7))
x2=np.zeros((7,7))
x[2,1]=1
x[2,2]=1
x[2,3]=1
x[2,4]=1
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [181]:
n=x.shape[0];m=x.shape[1]
n,m

(7, 7)

In [182]:
def alive(x,i,j):
    if(i>=0):
        if(i<=n-1):
            if(j>=0):
                if(j<=m-1):
                    return x[i,j]
    if(i<0):
        return 0
    if(j<0):
        return 0
    if(i>n-1):
        return 0
    if(j>m-1):
        return 0

In [183]:
def play(x,n,m):
    for i in range(n-1):
        for j in range(m-1):
            s=alive(x,i+1,j)+alive(x,i+1,j+1)+alive(x,i+1,j-1)+alive(x,i,j-1)+alive(x,i,j+1)+alive(x,i-1,j)+alive(x,i-1,j-1)+alive(x,i-1,j+1)
            s=int(s)
            #print(int(s))
            x2[i,j]=s
        
    for i in range(n-1):
        for j in range(m-1):
            if(x[i,j]==1):
                if(x2[i,j]!=2):
                    if(x2[i,j]!=3):
                        x[i,j]=0

    for i in range(n-1):
        for j in range(m-1):
            if(x[i,j]==0):
                if(x2[i,j]==3):
                    x[i,j]=1
    return(x)

In [186]:
for i in range(10):
    x=play(x,n,m)
    print("play: ",i)
    print(x)

play:  0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
play:  1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
play:  2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
play:  3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
play:  4
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
play:  5
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 